APP_NAME := "ecommerce-ui"
DOCKER_REGISTRY := "localhost:5005"

# build application
build:
    npm install
    npm run build

# build docker image
docker: build
    docker build -t {{APP_NAME}}:latest .
    docker tag {{APP_NAME}}:latest {{DOCKER_REGISTRY}}/{{APP_NAME}}:latest
    docker push {{DOCKER_REGISTRY}}/{{APP_NAME}}:latest
    docker images | grep "{{APP_NAME}}"

docker-run:
    docker run --rm -p 8080:80 {{APP_NAME}}:latest
